services:
  # web:
  #   image: node:20-alpine
  #   working_dir: /app
  #   volumes:
  #     - ./client:/app
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     HARDHAT_CONTRACT_ADRESS: ${HARDHAT_CONTRACT_ADRESS}
  #     GITHUB_ID: ${GITHUB_ID}
  #     GITHUB_SECRET: ${GITHUB_SECRET}
  #     AUTH_SECRET: ${AUTH_SECRET}
  #     DATABASE_URL: ${DATABASE_URL}
  #     HARDHAT_NETWORK: ${HARDHAT_NETWORK}
  #   command: >
  #     sh -c "
  #       yarn install &&
  #       npx prisma generate &&
  #       npx prisma migrate deploy &&    
  #       yarn build &&    
  #       yarn start
  #     "
  #   depends_on:
  #     - db
  #     - blockchain

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  blockchain:
    image: node:20-alpine
    working_dir: /blockchain
    volumes:
      - ./client:/blockchain
    ports:
      - "8545:8545"
    command: >
      sh -c "
        yarn install &&
        npx hardhat node &
        sleep 5 &&
        npx hardhat run src/app/data/context/blockchain/ethereum/scripts/deploy.js --network ${HARDHAT_NETWORK}
      "

volumes:
  postgres_data:
